# Generated by Django 5.2 on 2025-04-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_useranswer_selected_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='usersapp.submission'),
        ),
    ]
